name: Production Sveltekit App
on:
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job(IAM is required)
    steps:
    # Step 1
    - name: Check out code
      uses: actions/checkout@v2
    # Step 2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    # Step 3
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    # Step 4
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #ECR_REPOSITORY: docker_nodejs_demo
        IMAGE_TAG: node_api_latest
      run: |
        docker build -t $ECR_REGISTRY/ecs_frontend:$IMAGE_TAG .
        docker push $ECR_REGISTRY/ecs_frontend:$IMAGE_TAG